idf_component_register(
    SRCS "main.c"
         "ui_pixel.c"
         "ui_pixel_math.c"
         "slot_logic.c"
         "demo_slots.c"
         "slots_jie_hero.c"
         "slots_p3_hero.c"
         "slots_mari_hero.c"
         "slots_bgm_bank.c"
         "slots_ima_wav.c"
         "demo_display.c"
         "demo_button.c"
         "demo_audio.c"
         "demo_battery.c"
         "demo_radio.c"
         "demo_wifi.c"
         "demo_ble.c"
         "demo_low_power.c"
    INCLUDE_DIRS "."
    EMBED_FILES "slots_jie_hero.rgb565"
                "slots_jie_hero2.rgb565"
                "slots_jie_hero3.rgb565"
                "slots_p3_hero.rgb565"
                "slots_p3_hero2.rgb565"
                "slots_p3_hero3.rgb565"
                "slots_mari_hero.rgb565"
                "slots_mari_hero2.rgb565"
                "slots_mari_hero3.rgb565"
    REQUIRES bsp bt esp_event esp_hw_support esp_netif esp_partition esp_timer esp_wifi nvs_flash
)
